# Continuing interactivity in Python with the viz engine bqplot

Make sure you have installed this via the install script `test_imports_week01.ipynb` in week 1.  You may have to restart your jupyter or your browswer.

In [1]:
import bqplot
import numpy as np
import ipywidgets

Now we are going to mess around with some of the declaritive programming type options that bqplot can use.  This will rely heavily on the "Grammar of Graphics" constructs.

## Random line plot with Pan/Zoom interaction

Let's first start by creating data elements for our graphic just some random numbers:

In [4]:
x = np.arange(100) # integers 0->999
y = np.random.random(100) + 5 # random numbers with mean = 5

In [5]:
x, y

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
        51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
        68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
        85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]),
 array([5.25507595, 5.24739865, 5.54013814, 5.40069189, 5.21227059,
        5.34706208, 5.90283112, 5.04787661, 5.68320979, 5.66434966,
        5.68930295, 5.53036188, 5.84318471, 5.47831099, 5.11430586,
        5.71145703, 5.51580764, 5.15873227, 5.73671496, 5.13602923,
        5.39695247, 5.60794945, 5.47291409, 5.49373921, 5.5295593 ,
        5.84023235, 5.15972654, 5.23213136, 5.49087002, 5.09336178,
        5.94586405, 5.18045013, 5.33885234, 5.0845169 , 5.14293343,
        5.84059246, 5.43529888, 5.17821987, 5.24219675, 5.15387612,
      

Now we'll define some scale objects which will determine how lines will be drawn on our canvas:

In [6]:
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()

Now we are going to use GoG type calls to define what lines to actually draw combining information about our data and our scales:

In [7]:
lines = bqplot.Lines(x = x, y = y, scales = {'x': x_sc, 'y': y_sc})

Now, we are going to define what axis we want placed around the lines that we draw we'll draw both x & y axis.

In [8]:
ax_x = bqplot.Axis(scale = x_sc, label = 'X Value')
ax_y = bqplot.Axis(scale = y_sc, label = 'Y Value', orientation = 'vertical')

Finally, we combine all these things together into a bonified figure:

In [9]:
fig = bqplot.Figure(marks = [lines], axes = [ax_x, ax_y])
#display(fig) # you might also want to try "display"
# if you don't see the following fig, here is where
#  you might have to close and reopen your notebook
fig # note: just "fig" instead of "display(fig)" may also be an option for you

Figure(axes=[Axis(label='X Value', scale=LinearScale(), side='bottom'), Axis(label='Y Value', orientation='ver…

Ok, but this isn't interactive in anyway lets make it!!  There are a few "interactions" supported in `bqplot` but not all of them are supported for all types of plots.  The docs can be a little nebulous about what plot can use what type of interaction, so we'll just try a few and see what happens.  Here, let's add in an ability to pan/zoom in our plot:

In [10]:
pz = bqplot.interacts.PanZoom( scales = {'x': [x_sc], 'y': [y_sc]})

In [11]:
fig = bqplot.Figure(marks = [lines], axes = [ax_x, ax_y], interaction = pz)
#display(fig)
fig

Figure(axes=[Axis(label='X Value', scale=LinearScale(), side='bottom'), Axis(label='Y Value', orientation='ver…

Note that if I pan and zoom, the figure updates. Ooooo. fancy.

Note also, that the above figure also reacts as well this is because we are using the same lines & ax's objects -- recall back to last week that this was a feature of using ipywidgets and traitlets as well.

### SKIP this failure:

In [9]:
# lets see an example of where this can fail

# first lets make an x from 0-10 in 100 steps
x = np.mgrid[0.0:10.0:100j]
# and 2 y variables
y1 = x * 2
y2 = x**2

In [10]:
x_sc = bqplot.LinearScale(min = 1, max = 10)
# lets do one y-scale over linear and 1 over log
y_sc1 = bqplot.LinearScale(min = 1, max = 20)
y_sc2 = bqplot.LogScale(min = 1, max = 100)

In [11]:
# lets genrate lines for each y value
lines1 = bqplot.Lines(x = x, y = y1, scales = {'x': x_sc, 'y': y_sc1})
lines2 = bqplot.Lines(x = x, y = y2, scales = {'x': x_sc, 'y': y_sc2})

In [12]:
# and lets plot an x axis like before
ax_x = bqplot.Axis(scale = x_sc, label = 'X Value')
# and one y axis on the left
ax_y1 = bqplot.Axis(scale = y_sc1, label = 'Y1 Value', 
                    orientation = 'vertical')
# and one y-axis on the right
ax_y2 = bqplot.Axis(scale = y_sc2, label = 'Y2 Value', 
                    orientation = 'vertical', side = 'right')

In [13]:
# lets allow pan and zoom
pz = bqplot.interacts.PanZoom(scales = {'x': [x_sc], 
                                        'y': [y_sc1, y_sc2]})
#bqplot.interacts.PanZoom?
fig = bqplot.Figure(marks = [lines1, lines2], 
                    axes = [ax_x, ax_y1, ax_y2], interaction=pz)
#display(fig)
fig
# now we note if we zoom out too far, or pan to too negative of the x-axis
# we lose a line

# why? because the line is log-scaled, and log(numbers < 0) is undefined

# this is a way in which declaritive programming can fail because there
#  aren't obvious options to inhibit pan&zoom to a positive range

Figure(axes=[Axis(label='X Value', scale=LinearScale(max=10.0, min=1.0), side='bottom'), Axis(label='Y1 Value'…

### END SKIP

FYI lots of more fun notebooks here: https://github.com/dmadeka/PyGotham-2017

From video tutorial here: https://www.youtube.com/watch?v=rraXF0EjRC8

## Random Scatter plot
Ok, lets do another quick interactive example using a scatter plot:

In [12]:
x = np.random.random(100) # random points betweeon 0-1
y = np.random.random(100) # random points betweeon 0-1

In [13]:
x, y

(array([0.14079684, 0.24330252, 0.57350721, 0.36523191, 0.2350722 ,
        0.08525003, 0.34972248, 0.28301235, 0.61865135, 0.28260561,
        0.7391441 , 0.55284238, 0.19380775, 0.16872328, 0.26412005,
        0.27315221, 0.31592726, 0.58927717, 0.33887569, 0.99615732,
        0.32560868, 0.63553317, 0.76283313, 0.59889446, 0.41074735,
        0.89767118, 0.07377664, 0.74477844, 0.76305383, 0.1227426 ,
        0.1852518 , 0.86042645, 0.51922796, 0.7478363 , 0.9810829 ,
        0.21800506, 0.25657051, 0.53432913, 0.14622219, 0.38312611,
        0.40565494, 0.7686923 , 0.47068806, 0.2552812 , 0.52660194,
        0.12232872, 0.42823964, 0.81434295, 0.99208821, 0.83873003,
        0.96508687, 0.3154522 , 0.32670858, 0.37592421, 0.63011194,
        0.59592119, 0.22525385, 0.55357259, 0.36320139, 0.1776389 ,
        0.84264368, 0.04546308, 0.77328723, 0.73898989, 0.55467112,
        0.48824006, 0.88961112, 0.51463463, 0.47134635, 0.43702201,
        0.23310592, 0.09731933, 0.36925769, 0.41

Create scales and axis like we did before:

In [14]:
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()

x_ax = bqplot.Axis(scale = x_sc, label = 'X')
y_ax = bqplot.Axis(scale = y_sc, label = 'Y', orientation = 'vertical')

Create a scatter plot graphing object with these random x/y and scales:

In [15]:
scatters = bqplot.Scatter(x = x,
                          y = y,
                          scales = {'x': x_sc, 'y': y_sc})

Now, lets create a selector to select points along the x-axis.  We will use the `bqplot` interaction called `FastIntervalSelector`:

In [16]:
selector = bqplot.interacts.FastIntervalSelector(
            scale = x_sc, marks = [scatters]) 

Let's check out the full figure + interaction!

In [17]:
fig = bqplot.Figure(marks = [scatters], axes = [x_ax, y_ax], interaction = selector)
fig

Figure(axes=[Axis(label='X', scale=LinearScale(), side='bottom'), Axis(label='Y', orientation='vertical', scal…

How do we tell what interval we have selected?

In [18]:
selector.selected

array([0.3764567 , 0.65557666])

So, its a little hard to see what points are selected.  There are some hidden tags within our scatter plot points that we can mess with to change our our plot looks.  These have CSS styling (how HTML is styled), so they'll look very un-Pythonic, because they are!  We'll get more into this sort of thing when we are doing Javascript later in the course:

In [17]:
# we can also highlight what points we are selecting
scatters.unselected_style={'opacity': 0.8}
scatters.selected_style={'fill': 'red', 'stroke': 'yellow'}
# note we are selecing along the x-scale
fig = bqplot.Figure(marks = [scatters], axes = [x_ax, y_ax], interaction = selector)
display(fig)
# this might depend on what computer you are in, but on my mac, I click
#  to start selecting and then double click to "lock in" my selected
# region

Figure(axes=[Axis(label='X', scale=LinearScale(), side='bottom'), Axis(label='Y', orientation='vertical', scal…

In [18]:
# we can then print out what region is selected
selector.selected

array([0.41705861, 0.70855807])

In [19]:
# now, lets try some interactive histogramming of our buildings data
import pandas as pd
buildings = pd.read_csv("/Users/jillnaiman/Downloads/building_inventory.csv",
                        na_values = {'Year Acquired': 0, 
                                     'Year Constructed': 0, 
                                     'Square Footage': 0})

In [22]:
# since buildings is our data, we don't have to do anything
#  with that, but we do need to create our scales and 
# axes like we've been doing before:
# (1)
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()
x_ax = bqplot.Axis(scale = x_sc)
y_ax = bqplot.Axis(scale = y_sc, orientation = 'vertical')

# (2) now, lets do an interactive rebinning, but lets
# use bqplot and a slider widget to do it
hist = bqplot.Hist(sample = buildings["Year Acquired"],
            scales = {'sample': x_sc, 'count': y_sc},
                   bins = 128, normalized = True,
                   colors = ["#FFFFFF"])

# lets also create a slider like we've done before
islider = ipywidgets.IntSlider(min = 8, max = 128, step = 1)
# and lets link our sider and our bins of our histogram
ipywidgets.link((islider, 'value'), (hist, 'bins'))
# construct a fig
#fig = bqplot.Figure(marks = [hist], axes = [x_ax, y_ax])
# ***RUN NEXT CELL BEFORE ADDING 2ND HIST

# (3) ok, but maybe we want to see our original histogram
#  underneath, lets add this to our figure
hist2 = bqplot.Hist(sample = buildings["Year Acquired"],
                   opacity = 0.1, normalized = True,
            scales = {'sample': x_sc, 'count': y_sc},
                  bins = 128)
fig = bqplot.Figure(marks = [hist, hist2], axes = [x_ax, y_ax])

# for 2 & 3
#display(ipywidgets.VBox([fig, islider]))
ipywidgets.VBox([fig, islider])

# Activity #4: Wealth of Nations plot
* originially from the TedTalk: https://www.ted.com/talks/hans_rosling_shows_the_best_stats_you_ve_ever_seen
* found on Rosling's website: https://www.ted.com/talks/hans_rosling_shows_the_best_stats_you_ve_ever_seen
* We're going to make a tool similar to GapMinders:https://www.gapminder.org/world/
* Much of this is, in more detail, in the PyGothum-2017 github: https://github.com/dmadeka/PyGotham-2017 
* This will talk to javascript on the backend to mimic the output of another plotting package d3.js, but we don't have to learn about d3.js (just now) and can instead rely on our current Python knowledge

In [23]:
# import pandas if we have not
import pandas as pd

# lets start off our plot at the initial year of 1800
initial_year = 1800

In [24]:
# we'll read in our datafile and apply 
# some pre-written cleaning routines 
# get out the data we want for our plotting
from wealth_of_nations import process_data, get_min_max, get_data

# grab data
data = process_data('/Users/jillnaiman/Downloads/nations.json')

data

name               region  \
0          Angola   Sub-Saharan Africa   
1           Benin   Sub-Saharan Africa   
2        Botswana   Sub-Saharan Africa   
3    Burkina Faso   Sub-Saharan Africa   
4         Burundi   Sub-Saharan Africa   
..            ...                  ...   
174      Thailand  East Asia & Pacific   
175   Timor-Leste  East Asia & Pacific   
177         Tonga  East Asia & Pacific   
178       Vietnam  East Asia & Pacific   
179       Vanuatu  East Asia & Pacific   

                                                income  \
0    [359.93, 359.93, 359.93, 359.93, 359.93, 359.9...   
1    [553.72, 553.72, 553.72, 553.72, 553.72, 553.7...   
2    [407.36, 407.36, 407.36, 407.36, 407.36, 407.3...   
3    [454.33, 454.33, 454.33, 454.33, 454.33, 454.3...   
4    [447.59, 447.59, 447.59, 447.59, 447.59, 447.5...   
..                                                 ...   
174  [496.98, 496.98, 496.98, 496.98, 496.98, 496.9...   
175  [514.12, 514.3505, 514.581, 514.8115, 515.042,...   
177  [667.71, 667.71, 667.71, 667.71, 667.71, 667.7...   
178  [459.71, 459.71, 459.71, 459.71, 459.71, 459.7...   
179  [829.58, 829.58, 829.58, 829.58, 829.58, 829.5...   

                                            population  \
0    [1567028.0, 1567028.0, 1567028.0, 1567028.0, 1...   
1    [636559.0, 636559.0, 636559.0, 636559.0, 63655...   
2    [121000.0, 121000.0, 121000.0, 121000.0, 12100...   
3    [1665421.0, 1665421.0, 1665421.0, 1665421.0, 1...   
4    [899097.0, 899097.0, 899097.0, 899097.0, 89909...   
..                                                 ...   
174  [4665000.0, 4665000.0, 4665000.0, 4665000.0, 4...   
175  [137262.0, 137262.0, 137262.0, 137262.0, 13726...   
177  [18658.0, 18654.325581395347, 18650.6511627907...   
178  [6551000.0, 6551000.0, 6551000.0, 6551000.0, 6...   
179  [27791.0, 27791.0, 27791.0, 27791.0, 27791.0, ...   

                                        lifeExpectancy  
0    [26.98, 26.98, 26.98, 26.98, 26.98, 26.98, 26....  
1    [31.0, 31.0, 31.0, 31.0, 31.0, 31.0, 31.0, 31....  
2    [33.6, 33.6, 33.6, 33.6, 33.6, 33.6, 33.6, 33....  
3    [29.2, 29.2, 29.2, 29.2, 29.2, 29.2, 29.2, 29....  
4    [31.5, 31.5, 31.5, 31.5, 31.5, 31.5, 31.5, 31....  
..                                                 ...  
174  [30.4, 30.4, 30.4, 30.4, 30.4, 30.4, 30.4, 30....  
175  [28.97, 28.97, 28.97, 28.97, 28.97, 28.97, 28....  
177  [57.91, 57.91, 57.91, 57.91, 57.91, 57.91, 57....  
178  [32.0, 32.0, 32.0, 32.0, 32.0, 32.0, 32.0, 32....  
179  [40.8, 40.8, 40.8, 40.8, 40.8, 40.8, 40.8, 40....  

[178 rows x 5 columns]

In [25]:
# grab min & max values of our variables of interest
income_min, income_max, life_exp_min, life_exp_max, pop_min, pop_max = get_min_max(data)

In [26]:
# lets allow for a mouse-over interaction
# for silly:
import bqplot
tt = bqplot.Tooltip(fields=['name', 'x', 'y'], 
                    labels=['Country Name', 
                            'Income per Capita', 'Life Expectancy'])
#bqplot.Tooltip?

In [27]:
# we will label what year is being plotted, just like in the Gabminder plot
year_label = bqplot.Label(x=[0.75], y=[0.10], 
                   font_size=52, font_weight='bolder', 
                   colors=['orange'],
                   text=[str(initial_year)], enable_move=True)

In [86]:
# we'll define our scales like before
# here we scale our x & y axis to the scales of the min and max of our data
x_sc = bqplot.LogScale(min=income_min, max=income_max)
y_sc = bqplot.LinearScale(min=life_exp_min, max=life_exp_max)

# this is just something to color-code each circle by the region it corresponds to
#  (for example, asia, south america, africa, etc)
# the colors call is just mapping each catagorical variable to a color
c_sc = bqplot.OrdinalColorScale(domain=data['region'].unique().tolist(), 
                                colors=bqplot.CATEGORY10[:6])

# finally, we want the size of each of our dots to correspond to the population of 
# each country
#size_sc = bqplot.LinearScale(min=pop_min, max=pop_max)#, mid_range=0.1)
size_sc = bqplot.LinearScale(max=1326856173.0, min=2128.0)
#bqplot.LinearScale?

In [87]:
# create and label our x & y axis
ax_y = bqplot.Axis(label='Life Expectancy', scale=y_sc, 
                   orientation='vertical', side='left', 
                   grid_lines='solid')
ax_x = bqplot.Axis(label='Income per Capita', scale=x_sc, 
                   grid_lines='solid')

In [88]:
# now we'll use another little function from our library above to grab
# data for our initial setup (year = 1800)
# Start with the first year's data
cap_income, life_exp, pop = get_data(data,initial_year,initial_year)

In [89]:
# now lets make our scatter plot!
wealth_scat = bqplot.Scatter(x=cap_income, y=life_exp, 
                             color=data['region'], size=pop,
                      names=data['name'], display_names=False,
                      scales={'x': x_sc, 'y': y_sc, 'color': c_sc, 
                              'size': size_sc},
                      default_size=4112, tooltip=tt, 
                             animate=True, stroke='Black',
                      unhovered_style={'opacity': 0.5})
# much of these calls are things we've seen before, others will allow fun things 
#  like animation and also the ability to click on our plot and interact with it

In [90]:
# for our initial, 1800 view, we'll just allow the first "line" of the evolution of the 
# each nation's track to be displayed... this is essentially a place holder (visible = false)
nation_line = bqplot.Lines(x=data['income'][0], 
                           y=data['lifeExpectancy'][0], 
                           colors=['Gray'],
                       scales={'x': x_sc, 'y': y_sc}, visible=False)

In [91]:
# milliseconds of time between changes we make
time_interval = 10

In [92]:
# create the figure & 
fig = bqplot.Figure(marks=[wealth_scat, year_label, nation_line], 
                    axes=[ax_x, ax_y],
             title='Health and Wealth of Nations', 
                    animation_duration=time_interval)

# lets control the size in pixels too
fig.layout.min_width = '960px'
fig.layout.min_height = '640px'

In [93]:
# we'll use our friend the int slider to slide through years
# for silly:
import ipywidgets
year_slider = ipywidgets.IntSlider(min=1800, max=2008, step=1, description='Year', value=initial_year)

In [94]:
# make sure we define what happens when we change the year on our slider
def year_changed(change):
    wealth_scat.x, wealth_scat.y, wealth_scat.size = get_data(data,year_slider.value,initial_year)
    #wealth_scat.size+=1000
    year_label.text = [str(year_slider.value)]

year_slider.observe(year_changed, 'value')

In [95]:
# now we'll say what happens when we hover over an object
# we'll use "change" again to make it such that if a 
# user hovers over a country, the countries "life line" 
#  is visible
def hover_changed(change):
    if change.new is not None:
        nation_line.x = data['income'][change.new + 1]
        nation_line.y = data['lifeExpectancy'][change.new + 1]
        nation_line.visible = True
    else:
        nation_line.visible = False
        
wealth_scat.observe(hover_changed, 'hovered_point')

In [96]:
# finally, lets add a little play button so we can animate
#  what happens in time, just like on the d3.js plot
play_button = ipywidgets.Play(min=1800, max=2008, interval=time_interval)
# note, we use "jslink" because the "backend" here is javascript
#  bqplot is just interacting with javascript
ipywidgets.jslink((play_button, 'value'), (year_slider, 'value'))

In [97]:
# finally, lets put it all together!!

ipywidgets.VBox([ipywidgets.HBox([play_button, year_slider]), fig])

VkJveChjaGlsZHJlbj0oSEJveChjaGlsZHJlbj0oUGxheSh2YWx1ZT0xODAwLCBpbnRlcnZhbD0xMCwgbWF4PTIwMDgsIG1pbj0xODAwKSwgSW50U2xpZGVyKHZhbHVlPTE4MDAsIGRlc2NyaXDigKY=


In [98]:
pop_min, pop_max

(2128.0, 1326856173.0)

In [99]:
import bqplot
bqplot.Tooltip?