Let's import our usual things:

In [1]:
import bqplot
import numpy as np
import ipywidgets
%matplotlib inline

In [2]:
# generating random data, first for a line plot
x = np.arange(100) # integers 0->99
y = np.random.random(100) + 5

In [3]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [4]:
y

array([5.70635671, 5.03930155, 5.39517812, 5.06503291, 5.99000314,
       5.30844022, 5.14778745, 5.56049654, 5.95127541, 5.29031111,
       5.41240707, 5.98772101, 5.62492901, 5.72386883, 5.48080022,
       5.85178972, 5.05974412, 5.89081065, 5.80283272, 5.40473191,
       5.90423397, 5.34946917, 5.51799738, 5.73215745, 5.88730427,
       5.13076284, 5.37012709, 5.27165141, 5.74741654, 5.02221166,
       5.64104873, 5.2037555 , 5.7882892 , 5.77741368, 5.24257115,
       5.32143117, 5.92112559, 5.83251687, 5.9128743 , 5.61754822,
       5.43157681, 5.71432313, 5.01328999, 5.44679099, 5.53170192,
       5.76480903, 5.43614595, 5.88475663, 5.52850947, 5.54816343,
       5.83920454, 5.56944922, 5.32907948, 5.08031411, 5.77385833,
       5.43187291, 5.8691123 , 5.79886605, 5.3194119 , 5.46618662,
       5.56766139, 5.60360098, 5.12651835, 5.52015506, 5.74727565,
       5.38649463, 5.63551613, 5.27047557, 5.99074177, 5.80253222,
       5.68522039, 5.77123912, 5.69481507, 5.39787868, 5.76629

Our data is pretty linear, we have 2 scales & we want to do a line plot, so let's choose linear scales:

In [5]:
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()

In [7]:
bqplot.LinearScale?

Let's define our "mark" in this case a Line plot:

In [8]:
lines = bqplot.Lines(x=x, y=y, scales={'x': x_sc, 'y': y_sc})

Define my axis: 2 axis, one that is horizontal and on the bottom and one that is vertical and on the left side:

In [9]:
ax_x = bqplot.Axis(scale=x_sc, label='X Value')
ax_y = bqplot.Axis(scale=y_sc, label='Y Value', orientation='vertical')

In [10]:
bqplot.Axis?

Put everything together into a figure:

In [11]:
fig = bqplot.Figure(marks = [lines], axes=[ax_x, ax_y])
fig

Figure(axes=[Axis(label='X Value', scale=LinearScale(), side='bottom'), Axis(label='Y Value', orientation='ver…

In [12]:
# scales
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()

# marks
lines = bqplot.Lines(x=x, y=y, scales={'x': x_sc, 'y': y_sc})

# axis
ax_x = bqplot.Axis(scale=x_sc, label='X Value')
ax_y = bqplot.Axis(scale=y_sc, label='Y Value', orientation='vertical')

# construct fig
fig = bqplot.Figure(marks = [lines], axes=[ax_x, ax_y])
fig

Figure(axes=[Axis(label='X Value', scale=LinearScale()), Axis(label='Y Value', orientation='vertical', scale=L…

Adding in interactivity:

In [13]:
panzoom = bqplot.interacts.PanZoom( scales={'x':[x_sc], 'y':[y_sc]})

In [15]:
from IPython.display import display

In [16]:
fig = bqplot.Figure(marks=[lines], axes=[ax_x, ax_y], interaction=panzoom)
display(fig) # if figures are not showing, give this a shot

Figure(axes=[Axis(label='X Value', scale=LinearScale(max=112.59378383836136, min=13.692734354857162), side='bo…

## Scatter plot - with random numbers

In [17]:
x = np.random.random(100) # random points between 0->1
y = np.random.random(100) # random points between 0->1

In [21]:
# scales: linear because not doing colors yet or a log-space anything
x_sc = bqplot.LinearScale()
y_sc = bqplot.LinearScale()

# axes using these scales - just some scales on the left & bottom of the plot
x_ax = bqplot.Axis(scale = x_sc, label='X')
y_ax = bqplot.Axis(scale = y_sc, label='Y', orientation='vertical')

In [22]:
# marks: will be a scatter plot
scatters = bqplot.Scatter(x=x, y=y, scales={'x':x_sc, 'y':y_sc})

In [23]:
# adding in an interaction now: select points on the x-axis
selector = bqplot.interacts.FastIntervalSelector(scale=x_sc, marks=[scatters])

In [24]:
# put it all together in a figure!
fig = bqplot.Figure(marks=[scatters], axes=[x_ax, y_ax], interaction=selector)
fig

Figure(axes=[Axis(label='X', scale=LinearScale(), side='bottom'), Axis(label='Y', orientation='vertical', scal…

In [25]:
selector.keys

['_model_module',
 '_model_module_version',
 '_model_name',
 '_view_count',
 '_view_module',
 '_view_module_version',
 '_view_name',
 'color',
 'marks',
 'scale',
 'selected',
 'size']

In [27]:
selector.selected # this is a trait that we can "watch" like before

array([0.32938296, 0.81524344])

In [28]:
# we can play with how our selection looks:
scatters.unselected_style={'opacity':0.8} # unselected a little see-through
scatters.selected_style={'fill':'red', 'stroke':'yellow'}

In [29]:
fig = bqplot.Figure(marks=[scatters], axes=[x_ax,y_ax], interaction=selector)
fig

Figure(axes=[Axis(label='X', scale=LinearScale(), side='bottom'), Axis(label='Y', orientation='vertical', scal…

## Gridheatmap mark

In [30]:
# define the data
data = np.random.random((10,10))

In [32]:
data.shape

(10, 10)

In [33]:
# step 1: define a scale, in this case color
col_sc = bqplot.ColorScale() # like x/y but color

# step2: I am ignoring axes for now

# step 3: gridheatmap mark
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc})

# step 4: interaction, but ignoring for now too

# step 5: put it all togehter in a figure
fig = bqplot.Figure(marks=[heat_map])
fig

Figure(fig_margin={'top': 60, 'bottom': 60, 'left': 60, 'right': 60}, marks=[GridHeatMap(color=array([[0.81919…

In [34]:
# step 1: define a scale, in this case color
col_sc = bqplot.ColorScale(scheme="Reds") # like x/y but color

# step2: I am ignoring axes for now

# step 3: gridheatmap mark
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc})

# step 4: interaction, but ignoring for now too

# step 5: put it all togehter in a figure
fig = bqplot.Figure(marks=[heat_map])
fig

Figure(fig_margin={'top': 60, 'bottom': 60, 'left': 60, 'right': 60}, marks=[GridHeatMap(color=array([[0.81919…

In [35]:
# step 1: define a scale, in this case color
col_sc = bqplot.ColorScale(scheme="Reds") # like x/y but color

# step2: I am ignoring axes for now
# first axis will be for color
c_ax = bqplot.ColorAxis(scale = col_sc, 
                       orientation = 'vertical', 
                       side = 'right')

# step 3: gridheatmap mark
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc})

# step 4: interaction, but ignoring for now too

# step 5: put it all togehter in a figure
fig = bqplot.Figure(marks=[heat_map], axes = [c_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Reds'), side='right')], fig_margin={'t…

Adding in x/y labels -> set their scales and axis

In [36]:
# step 1: define a scale, in this case color
col_sc = bqplot.ColorScale(scheme="Reds") # like x/y but color
x_sc = bqplot.OrdinalScale() # because bins are more categorical than numerical
y_sc = bqplot.OrdinalScale() # ... we are using a 10x10 grid of numbers, these will be bin #

# step2: I am ignoring axes for now
# first axis will be for color
c_ax = bqplot.ColorAxis(scale = col_sc, 
                       orientation = 'vertical', 
                       side = 'right')
# adding in x/y axis with labels
x_ax = bqplot.Axis(scale = x_sc)
y_ax = bqplot.Axis(scale = y_sc, orientation='vertical')

# step 3: gridheatmap mark
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc, 
                                                 'row': y_sc,
                                                 'column': x_sc})

# step 4: interaction, but ignoring for now too

# step 5: put it all togehter in a figure
fig = bqplot.Figure(marks=[heat_map], axes = [c_ax, x_ax, y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Reds'), side='right'), Axis(scale=Ordi…

In [40]:
# step 1: define a scale, in this case color
col_sc = bqplot.ColorScale(scheme="Reds") # like x/y but color
x_sc = bqplot.OrdinalScale() # because bins are more categorical than numerical
y_sc = bqplot.OrdinalScale() # ... we are using a 10x10 grid of numbers, these will be bin #

# step2: I am ignoring axes for now
# first axis will be for color
c_ax = bqplot.ColorAxis(scale = col_sc, 
                       orientation = 'vertical', 
                       side = 'right')
# adding in x/y axis with labels
x_ax = bqplot.Axis(scale = x_sc)
y_ax = bqplot.Axis(scale = y_sc, orientation='vertical')

# step 3: gridheatmap mark
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc, 
                                                 'row': y_sc,
                                                 'column': x_sc}, 
                             interactions={'click':'select'}, # an interaction associated with GHM
                             anchor_style = {'fill':'blue'}) 

# step 4: interaction, but ignoring for now too

# step 5: put it all togehter in a figure
fig = bqplot.Figure(marks=[heat_map], axes = [c_ax, x_ax, y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Reds'), side='right'), Axis(scale=Ordi…

In [43]:
heat_map.selected # trait of my heatmap -> can use selection to drive updates

array([[3, 4]])

Use our selection to change the value of a ipywidgets.Label (print out data value)

In [44]:
mySelectedLabel = ipywidgets.Label()

In [46]:
mySelectedLabel.value = 'Hi I am widget'
mySelectedLabel

Label(value='Hi I am widget')

In [48]:
# we will just print out whatever "change" is when a grid is selected on gridheatmap
def on_selected(change):
    print(change)

In [49]:
# step 1: define a scale, in this case color
col_sc = bqplot.ColorScale(scheme="Reds") # like x/y but color
x_sc = bqplot.OrdinalScale() # because bins are more categorical than numerical
y_sc = bqplot.OrdinalScale() # ... we are using a 10x10 grid of numbers, these will be bin #

# step2: I am ignoring axes for now
# first axis will be for color
c_ax = bqplot.ColorAxis(scale = col_sc, 
                       orientation = 'vertical', 
                       side = 'right')
# adding in x/y axis with labels
x_ax = bqplot.Axis(scale = x_sc)
y_ax = bqplot.Axis(scale = y_sc, orientation='vertical')

# step 3: gridheatmap mark
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc, 
                                                 'row': y_sc,
                                                 'column': x_sc}, 
                             interactions={'click':'select'}, # an interaction associated with GHM
                             anchor_style = {'fill':'blue'}) 

# step 4: interaction
# -> we actually defined this in the mark making call in step 3
# now we have to define what "action" happens
heat_map.observe(on_selected, 'selected')

# step 5: put it all togehter in a figure
fig = bqplot.Figure(marks=[heat_map], axes = [c_ax, x_ax, y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Reds'), side='right'), Axis(scale=Ordi…

{'name': 'selected', 'old': None, 'new': array([[9, 1]]), 'owner': GridHeatMap(anchor_style={'fill': 'blue'}, color=array([[0.81919382, 0.99622246, 0.08135958, 0.60264496, 0.37817103,
        0.90677554, 0.40405674, 0.89391348, 0.4961305 , 0.92402948],
       [0.81820656, 0.17425324, 0.49035235, 0.37428901, 0.16130252,
        0.11128103, 0.08305745, 0.30748096, 0.64131375, 0.60045082],
       [0.26112295, 0.59169297, 0.36762429, 0.11297529, 0.87385117,
        0.89740878, 0.11968837, 0.68624103, 0.05624693, 0.15498439],
       [0.45251591, 0.43733605, 0.71688318, 0.04578347, 0.5357737 ,
        0.49839827, 0.53770759, 0.5736234 , 0.71613683, 0.8627081 ],
       [0.46182623, 0.97039187, 0.06966527, 0.12220345, 0.63776615,
        0.37749169, 0.55987587, 0.06970454, 0.30961644, 0.08266948],
       [0.21320311, 0.30790291, 0.83036939, 0.50957139, 0.8181664 ,
        0.46253667, 0.31640393, 0.61079946, 0.17448329, 0.36096526],
       [0.98972671, 0.3168095 , 0.78212644, 0.60416984, 0.3340

In [51]:
# update our on_selected function to print out what is actually selected (indices)
def on_selected(change):
    print(change['owner'].selected) # print heatmap selected key

In [52]:
# step 1: define a scale, in this case color
col_sc = bqplot.ColorScale(scheme="Reds") # like x/y but color
x_sc = bqplot.OrdinalScale() # because bins are more categorical than numerical
y_sc = bqplot.OrdinalScale() # ... we are using a 10x10 grid of numbers, these will be bin #

# step2: I am ignoring axes for now
# first axis will be for color
c_ax = bqplot.ColorAxis(scale = col_sc, 
                       orientation = 'vertical', 
                       side = 'right')
# adding in x/y axis with labels
x_ax = bqplot.Axis(scale = x_sc)
y_ax = bqplot.Axis(scale = y_sc, orientation='vertical')

# step 3: gridheatmap mark
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc, 
                                                 'row': y_sc,
                                                 'column': x_sc}, 
                             interactions={'click':'select'}, # an interaction associated with GHM
                             anchor_style = {'fill':'blue'}) 

# step 4: interaction
# -> we actually defined this in the mark making call in step 3
# now we have to define what "action" happens
heat_map.observe(on_selected, 'selected')

# step 5: put it all togehter in a figure
fig = bqplot.Figure(marks=[heat_map], axes = [c_ax, x_ax, y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Reds'), side='right'), Axis(scale=Ordi…

[[2 2]]
[[2 1]]
[[2 2]
 [2 1]]
[[1 2]
 [1 1]
 [2 1]
 [2 2]]
[[2 6]]


In [53]:
# we only want to deal with selections of one grid
# ignore any SHIFT-selects
def on_selected(change):
    if len(change['owner'].selected) == 1: # only selecting 1 element at a time
        print(change['owner'].selected[0]) # print just the first index selected

In [54]:
# step 1: define a scale, in this case color
col_sc = bqplot.ColorScale(scheme="Reds") # like x/y but color
x_sc = bqplot.OrdinalScale() # because bins are more categorical than numerical
y_sc = bqplot.OrdinalScale() # ... we are using a 10x10 grid of numbers, these will be bin #

# step2: I am ignoring axes for now
# first axis will be for color
c_ax = bqplot.ColorAxis(scale = col_sc, 
                       orientation = 'vertical', 
                       side = 'right')
# adding in x/y axis with labels
x_ax = bqplot.Axis(scale = x_sc)
y_ax = bqplot.Axis(scale = y_sc, orientation='vertical')

# step 3: gridheatmap mark
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc, 
                                                 'row': y_sc,
                                                 'column': x_sc}, 
                             interactions={'click':'select'}, # an interaction associated with GHM
                             anchor_style = {'fill':'blue'}) 

# step 4: interaction
# -> we actually defined this in the mark making call in step 3
# now we have to define what "action" happens
heat_map.observe(on_selected, 'selected')

# step 5: put it all togehter in a figure
fig = bqplot.Figure(marks=[heat_map], axes = [c_ax, x_ax, y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Reds'), side='right'), Axis(scale=Ordi…

[2 3]
[3 2]
[1 4]
[1 5]
[2 5]
[3 1]
[2 4]
[2 7]


In [55]:
# Let's grab our datavalue at this location and then set our ipywidget.Label to
#.  display this value

# we only want to deal with selections of one grid
# ignore any SHIFT-selects
def on_selected(change):
    if len(change['owner'].selected) == 1: # only selecting 1 element at a time
        #print(change['owner'].selected[0]) # print just the first index selected
        j, i = change['owner'].selected[0] # y & x indicies
        v = data[i,j] # x, y indicies, grab data value at this location
        mySelectedLabel.value = 'Data Value = ' + str(v) # update widget label with this value

In [56]:
# step 1: define a scale, in this case color
col_sc = bqplot.ColorScale(scheme="Reds") # like x/y but color
x_sc = bqplot.OrdinalScale() # because bins are more categorical than numerical
y_sc = bqplot.OrdinalScale() # ... we are using a 10x10 grid of numbers, these will be bin #

# step2: I am ignoring axes for now
# first axis will be for color
c_ax = bqplot.ColorAxis(scale = col_sc, 
                       orientation = 'vertical', 
                       side = 'right')
# adding in x/y axis with labels
x_ax = bqplot.Axis(scale = x_sc)
y_ax = bqplot.Axis(scale = y_sc, orientation='vertical')

# step 3: gridheatmap mark
heat_map = bqplot.GridHeatMap(color=data, scales={'color':col_sc, 
                                                 'row': y_sc,
                                                 'column': x_sc}, 
                             interactions={'click':'select'}, # an interaction associated with GHM
                             anchor_style = {'fill':'blue'}) 

# step 4: interaction
# -> we actually defined this in the mark making call in step 3
# now we have to define what "action" happens
heat_map.observe(on_selected, 'selected')

# step 5: put it all togehter in a figure
fig = bqplot.Figure(marks=[heat_map], axes = [c_ax, x_ax, y_ax])
#fig

In [58]:
# use a vertical box to stack both the label and the figure
myDashboard = ipywidgets.VBox([mySelectedLabel, fig])
myDashboard

## 3D data -> dashboard

In [59]:
data = np.random.random( (10, 10, 20))

In [61]:
data.shape

(10, 10, 20)

Starting back with our base heatmap:

In [62]:
# step 1: define a scale, in this case color
col_sc = bqplot.ColorScale(scheme="Reds") # like x/y but color
x_sc = bqplot.OrdinalScale() # because bins are more categorical than numerical
y_sc = bqplot.OrdinalScale() # .. we are using a 10x10 grid of numbers, these will be bin #

# step2: I am ignoring axes for now
# first axis will be for color
c_ax = bqplot.ColorAxis(scale = col_sc, 
                       orientation = 'vertical', 
                       side = 'right')
# adding in x/y axis with labels
x_ax = bqplot.Axis(scale = x_sc)
y_ax = bqplot.Axis(scale = y_sc, orientation='vertical')

# step 3: gridheatmap mark
heat_map = bqplot.GridHeatMap(color=np.sum(data,axis=2), scales={'color':col_sc, 
                                                 'row': y_sc,
                                                 'column': x_sc}, 
                             interactions={'click':'select'}, # an interaction associated with GHM
                             anchor_style = {'fill':'blue'}) 

# step 4: interaction
# -> we actually defined this in the mark making call in step 3
# now we have to define what "action" happens
heat_map.observe(on_selected, 'selected')

# step 5: put it all togehter in a figure
fig = bqplot.Figure(marks=[heat_map], axes = [c_ax, x_ax, y_ax])
fig

Figure(axes=[ColorAxis(orientation='vertical', scale=ColorScale(scheme='Reds'), side='right'), Axis(scale=Ordi…

In [75]:
mySelectedLabel = ipywidgets.Label()

In [76]:
# Let's grab our datavalue at this location and then set our ipywidget.Label to
#  display this value

# we only want to deal with selections of one grid
# ignore any SHIFT-selects
def on_selected_3d(change):
    if len(change['owner'].selected) == 1: # only selecting 1 element at a time
        j, i = change['owner'].selected[0] # y & x indicies
        v = data[i,j].sum() # x, y indicies, grab data value at this location
        mySelectedLabel.value = 'Data Sum = ' + str(v) # update widget label with this value

In [77]:
# step 1: define a scale, in this case color
col_sc = bqplot.ColorScale(scheme="Reds") # like x/y but color
x_sc = bqplot.OrdinalScale() # because bins are more categorical than numerical
y_sc = bqplot.OrdinalScale() # .. we are using a 10x10 grid of numbers, these will be bin #

# step2: I am ignoring axes for now
# first axis will be for color
c_ax = bqplot.ColorAxis(scale = col_sc, 
                       orientation = 'vertical', 
                       side = 'right')
# adding in x/y axis with labels
x_ax = bqplot.Axis(scale = x_sc)
y_ax = bqplot.Axis(scale = y_sc, orientation='vertical')

# step 3: gridheatmap mark
heat_map = bqplot.GridHeatMap(color=np.sum(data,axis=2), scales={'color':col_sc, 
                                                 'row': y_sc,
                                                 'column': x_sc}, 
                             interactions={'click':'select'}, # an interaction associated with GHM
                             anchor_style = {'fill':'blue'}) 

# step 4: interaction
# -> we actually defined this in the mark making call in step 3
# now we have to define what "action" happens
heat_map.observe(on_selected_3d, 'selected')

# step 5: put it all togehter in a figure
fig = bqplot.Figure(marks=[heat_map], axes = [c_ax, x_ax, y_ax])
#fig

In [78]:
# use a vertical box to stack both the label and the figure
myDashboard = ipywidgets.VBox([mySelectedLabel, fig])
myDashboard

Let's start with just 1 histogram at one x/y index:

In [79]:
i, j = 0,0 # selecting the 20 points at x/y = 0,0

In [81]:
# step 1: scales for histogram
x_sch = bqplot.LinearScale() # range of data along Z -axis => 0->1
y_sch = bqplot.LinearScale() # frequency, counts

# step 2: axis for histogram
x_axh = bqplot.Axis(scale = x_sch, label='Value of 3rd axis')
y_axh = bqplot.Axis(scale = y_sch, 
                   orientation='vertical',
                   label = 'Frequency')

# step 3: marks => histogram
hist = bqplot.Hist(sample=data[i,j,:], # sample is required for mark of Histogram
                  normalized=False, # plotting frequency not prob. distribution
                  scales={'sample':x_sch, 'count':y_sch}, 
                  bins=5)

In [82]:
# let's take a look
# step 4: no interactions (because we want changes in gridheapmap to drive changes in hist)

# step 5: put it all together
fig_hist = bqplot.Figure(marks=[hist], axes=[x_axh, y_axh])
fig_hist

Figure(axes=[Axis(label='Value of 3rd axis', scale=LinearScale(), side='bottom'), Axis(label='Frequency', orie…

In [84]:
hist.sample

array([0.9511319 , 0.38342102, 0.13180398, 0.467372  , 0.87930711,
       0.21056163, 0.63465908, 0.06243695, 0.27375508, 0.70833129,
       0.04303475, 0.84368255, 0.98652019, 0.20432917, 0.33958188,
       0.97226996, 0.02692581, 0.01815797, 0.91364864, 0.61864666])

We want to update this sample based on what is selected in our GridHeatMap.

Define what is happening when we select something:

In [86]:
# Let's grab our datavalue at this location and then set our ipywidget.Label to
#  display this value

# we only want to deal with selections of one grid
# ignore any SHIFT-selects
def on_selected_3d(change):
    if len(change['owner'].selected) == 1: # only selecting 1 element at a time
        j, i = change['owner'].selected[0] # y & x indicies
        v = data[i,j].sum() # x, y indicies, grab data value at this location
        mySelectedLabel.value = 'Data Sum = ' + str(v) # update widget label with this value
        # now including updates to the histogram sample key
        hist.sample = data[i,j,:]

Now create the heat-map and observe for selection => when selection happens update everything else based on the 'selected' trait of the gridheatmap:

In [87]:
# step 1: define a scale, in this case color
col_sc = bqplot.ColorScale(scheme="Reds") # like x/y but color
x_sc = bqplot.OrdinalScale() # because bins are more categorical than numerical
y_sc = bqplot.OrdinalScale() # .. we are using a 10x10 grid of numbers, these will be bin #

# step2: I am ignoring axes for now
# first axis will be for color
c_ax = bqplot.ColorAxis(scale = col_sc, 
                       orientation = 'vertical', 
                       side = 'right')
# adding in x/y axis with labels
x_ax = bqplot.Axis(scale = x_sc)
y_ax = bqplot.Axis(scale = y_sc, orientation='vertical')

# step 3: gridheatmap mark
heat_map = bqplot.GridHeatMap(color=np.sum(data,axis=2), scales={'color':col_sc, 
                                                 'row': y_sc,
                                                 'column': x_sc}, 
                             interactions={'click':'select'}, # an interaction associated with GHM
                             anchor_style = {'fill':'blue'}) 

# step 4: interaction
# -> we actually defined this in the mark making call in step 3
# now we have to define what "action" happens
heat_map.observe(on_selected_3d, 'selected')

# step 5: put it all togehter in a figure
fig = bqplot.Figure(marks=[heat_map], axes = [c_ax, x_ax, y_ax])
#fig

Just for fun: re-create the histogram:

In [88]:
# step 1: scales for histogram
x_sch = bqplot.LinearScale() # range of data along Z -axis => 0->1
y_sch = bqplot.LinearScale() # frequency, counts

# step 2: axis for histogram
x_axh = bqplot.Axis(scale = x_sch, label='Value of 3rd axis')
y_axh = bqplot.Axis(scale = y_sch, 
                   orientation='vertical',
                   label = 'Frequency')

# step 3: marks => histogram
hist = bqplot.Hist(sample=data[i,j,:], # sample is required for mark of Histogram
                  normalized=False, # plotting frequency not prob. distribution
                  scales={'sample':x_sch, 'count':y_sch}, 
                  bins=5)

# let's take a look
# step 4: no interactions (because we want changes in gridheapmap to drive changes in hist)

# step 5: put it all together
fig_hist = bqplot.Figure(marks=[hist], axes=[x_axh, y_axh])

In [92]:
# layout - nested HBox & VBox
figures = ipywidgets.HBox([fig, fig_hist])

# change how big my figures appear on my output
fig.layout.min_width='400px'
fig_hist.layout.min_width='400px'

# dashboard
myDashboard = ipywidgets.VBox([mySelectedLabel, figures])
myDashboard